// Code generated by rugo dev bridgegen; DO NOT EDIT.

package gobridge

func init() {
	Register(&Package{
		Path: "encoding/base64",
		Doc:  "Functions from Go's encoding/base64 package.",
		Funcs: map[string]GoFuncSig{
			"raw_std_encoding_decoded_len":      {GoName: "RawStdEncoding.DecodedLen", Params: []GoType{GoInt}, Returns: []GoType{GoInt}},
			"raw_std_encoding_encoded_len":      {GoName: "RawStdEncoding.EncodedLen", Params: []GoType{GoInt}, Returns: []GoType{GoInt}},
			"raw_url_encoding_decoded_len":      {GoName: "RawURLEncoding.DecodedLen", Params: []GoType{GoInt}, Returns: []GoType{GoInt}},
			"raw_url_encoding_encoded_len":      {GoName: "RawURLEncoding.EncodedLen", Params: []GoType{GoInt}, Returns: []GoType{GoInt}},
			"std_encoding_decoded_len":          {GoName: "StdEncoding.DecodedLen", Params: []GoType{GoInt}, Returns: []GoType{GoInt}},
			"std_encoding_encoded_len":          {GoName: "StdEncoding.EncodedLen", Params: []GoType{GoInt}, Returns: []GoType{GoInt}},
			"url_encoding_decoded_len":          {GoName: "URLEncoding.DecodedLen", Params: []GoType{GoInt}, Returns: []GoType{GoInt}},
			"url_encoding_encoded_len":          {GoName: "URLEncoding.EncodedLen", Params: []GoType{GoInt}, Returns: []GoType{GoInt}},
			"raw_std_encoding_append_decode":    {GoName: "RawStdEncoding.AppendDecode", Params: []GoType{GoByteSlice, GoByteSlice}, Returns: []GoType{GoByteSlice, GoError}},
			"raw_std_encoding_append_encode":    {GoName: "RawStdEncoding.AppendEncode", Params: []GoType{GoByteSlice, GoByteSlice}, Returns: []GoType{GoByteSlice}},
			"raw_std_encoding_decode":           {GoName: "RawStdEncoding.Decode", Params: []GoType{GoByteSlice, GoByteSlice}, Returns: []GoType{GoInt, GoError}},
			"raw_std_encoding_decode_string":    {GoName: "RawStdEncoding.DecodeString", Params: []GoType{GoString}, Returns: []GoType{GoByteSlice, GoError}},
			"raw_std_encoding_encode":           {GoName: "RawStdEncoding.Encode", Params: []GoType{GoByteSlice, GoByteSlice}, Returns: nil},
			"raw_std_encoding_encode_to_string": {GoName: "RawStdEncoding.EncodeToString", Params: []GoType{GoByteSlice}, Returns: []GoType{GoString}},
			"raw_url_encoding_append_decode":    {GoName: "RawURLEncoding.AppendDecode", Params: []GoType{GoByteSlice, GoByteSlice}, Returns: []GoType{GoByteSlice, GoError}},
			"raw_url_encoding_append_encode":    {GoName: "RawURLEncoding.AppendEncode", Params: []GoType{GoByteSlice, GoByteSlice}, Returns: []GoType{GoByteSlice}},
			"raw_url_encoding_decode":           {GoName: "RawURLEncoding.Decode", Params: []GoType{GoByteSlice, GoByteSlice}, Returns: []GoType{GoInt, GoError}},
			"raw_url_encoding_decode_string":    {GoName: "RawURLEncoding.DecodeString", Params: []GoType{GoString}, Returns: []GoType{GoByteSlice, GoError}},
			"raw_url_encoding_encode":           {GoName: "RawURLEncoding.Encode", Params: []GoType{GoByteSlice, GoByteSlice}, Returns: nil},
			"raw_url_encoding_encode_to_string": {GoName: "RawURLEncoding.EncodeToString", Params: []GoType{GoByteSlice}, Returns: []GoType{GoString}},
			"std_encoding_append_decode":        {GoName: "StdEncoding.AppendDecode", Params: []GoType{GoByteSlice, GoByteSlice}, Returns: []GoType{GoByteSlice, GoError}},
			"std_encoding_append_encode":        {GoName: "StdEncoding.AppendEncode", Params: []GoType{GoByteSlice, GoByteSlice}, Returns: []GoType{GoByteSlice}},
			"std_encoding_decode":               {GoName: "StdEncoding.Decode", Params: []GoType{GoByteSlice, GoByteSlice}, Returns: []GoType{GoInt, GoError}},
			"std_encoding_decode_string":        {GoName: "StdEncoding.DecodeString", Params: []GoType{GoString}, Returns: []GoType{GoByteSlice, GoError}},
			"std_encoding_encode":               {GoName: "StdEncoding.Encode", Params: []GoType{GoByteSlice, GoByteSlice}, Returns: nil},
			"std_encoding_encode_to_string":     {GoName: "StdEncoding.EncodeToString", Params: []GoType{GoByteSlice}, Returns: []GoType{GoString}},
			"url_encoding_append_decode":        {GoName: "URLEncoding.AppendDecode", Params: []GoType{GoByteSlice, GoByteSlice}, Returns: []GoType{GoByteSlice, GoError}},
			"url_encoding_append_encode":        {GoName: "URLEncoding.AppendEncode", Params: []GoType{GoByteSlice, GoByteSlice}, Returns: []GoType{GoByteSlice}},
			"url_encoding_decode":               {GoName: "URLEncoding.Decode", Params: []GoType{GoByteSlice, GoByteSlice}, Returns: []GoType{GoInt, GoError}},
			"url_encoding_decode_string":        {GoName: "URLEncoding.DecodeString", Params: []GoType{GoString}, Returns: []GoType{GoByteSlice, GoError}},
			"url_encoding_encode":               {GoName: "URLEncoding.Encode", Params: []GoType{GoByteSlice, GoByteSlice}, Returns: nil},
			"url_encoding_encode_to_string":     {GoName: "URLEncoding.EncodeToString", Params: []GoType{GoByteSlice}, Returns: []GoType{GoString}},
			// --- Skipped (need custom Codegen or _custom.go) ---
			// new_decoder (blocked): param 0: pointer to encoding/base64.Encoding
			// new_encoder (blocked): param 0: pointer to encoding/base64.Encoding
			// new_encoding (blocked): return 0: pointer to encoding/base64.Encoding
			// raw_std_encoding_strict (blocked): return 0: pointer to encoding/base64.Encoding
			// raw_std_encoding_with_padding (blocked): return 0: pointer to encoding/base64.Encoding
			// raw_url_encoding_strict (blocked): return 0: pointer to encoding/base64.Encoding
			// raw_url_encoding_with_padding (blocked): return 0: pointer to encoding/base64.Encoding
			// std_encoding_strict (blocked): return 0: pointer to encoding/base64.Encoding
			// std_encoding_with_padding (blocked): return 0: pointer to encoding/base64.Encoding
			// url_encoding_strict (blocked): return 0: pointer to encoding/base64.Encoding
			// url_encoding_with_padding (blocked): return 0: pointer to encoding/base64.Encoding
		},
	})
}
