// Code generated by rugo dev bridgegen; DO NOT EDIT.

package gobridge

func init() {
	Register(&Package{
		Path: "path/filepath",
		Doc:  "Functions from Go's path/filepath package.",
		Funcs: map[string]GoFuncSig{
			"abs":           {GoName: "Abs", Params: []GoType{GoString}, Returns: []GoType{GoString, GoError}},
			"base":          {GoName: "Base", Params: []GoType{GoString}, Returns: []GoType{GoString}},
			"clean":         {GoName: "Clean", Params: []GoType{GoString}, Returns: []GoType{GoString}},
			"dir":           {GoName: "Dir", Params: []GoType{GoString}, Returns: []GoType{GoString}},
			"eval_symlinks": {GoName: "EvalSymlinks", Params: []GoType{GoString}, Returns: []GoType{GoString, GoError}},
			"ext":           {GoName: "Ext", Params: []GoType{GoString}, Returns: []GoType{GoString}},
			"from_slash":    {GoName: "FromSlash", Params: []GoType{GoString}, Returns: []GoType{GoString}},
			"glob":          {GoName: "Glob", Params: []GoType{GoString}, Returns: []GoType{GoStringSlice, GoError}},
			"has_prefix":    {GoName: "HasPrefix", Params: []GoType{GoString, GoString}, Returns: []GoType{GoBool}},
			"is_abs":        {GoName: "IsAbs", Params: []GoType{GoString}, Returns: []GoType{GoBool}},
			"is_local":      {GoName: "IsLocal", Params: []GoType{GoString}, Returns: []GoType{GoBool}},
			"join":          {GoName: "Join", Params: []GoType{GoStringSlice}, Returns: []GoType{GoString}, Variadic: true},
			"localize":      {GoName: "Localize", Params: []GoType{GoString}, Returns: []GoType{GoString, GoError}},
			"match":         {GoName: "Match", Params: []GoType{GoString, GoString}, Returns: []GoType{GoBool, GoError}},
			"rel":           {GoName: "Rel", Params: []GoType{GoString, GoString}, Returns: []GoType{GoString, GoError}},
			"split":         {GoName: "Split", Params: []GoType{GoString}, Returns: []GoType{GoString, GoString}},
			"split_list":    {GoName: "SplitList", Params: []GoType{GoString}, Returns: []GoType{GoStringSlice}},
			"to_slash":      {GoName: "ToSlash", Params: []GoType{GoString}, Returns: []GoType{GoString}},
			"volume_name":   {GoName: "VolumeName", Params: []GoType{GoString}, Returns: []GoType{GoString}},
			// --- Skipped (need custom Codegen or _custom.go) ---
			// walk (func): param 1: func with unbridgeable signature
			// walk_dir (func): param 1: func with unbridgeable signature
		},
	})
}
