// Code generated by rugo dev bridgegen; DO NOT EDIT.

package gobridge

func init() {
	Register(&Package{
		Path: "encoding/hex",
		Doc:  "Functions from Go's encoding/hex package.",
		Funcs: map[string]GoFuncSig{
			"decoded_len":      {GoName: "DecodedLen", Params: []GoType{GoInt}, Returns: []GoType{GoInt}},
			"encoded_len":      {GoName: "EncodedLen", Params: []GoType{GoInt}, Returns: []GoType{GoInt}},
			"append_decode":    {GoName: "AppendDecode", Params: []GoType{GoByteSlice, GoByteSlice}, Returns: []GoType{GoByteSlice, GoError}},
			"append_encode":    {GoName: "AppendEncode", Params: []GoType{GoByteSlice, GoByteSlice}, Returns: []GoType{GoByteSlice}},
			"decode":           {GoName: "Decode", Params: []GoType{GoByteSlice, GoByteSlice}, Returns: []GoType{GoInt, GoError}},
			"decode_string":    {GoName: "DecodeString", Params: []GoType{GoString}, Returns: []GoType{GoByteSlice, GoError}},
			"dump":             {GoName: "Dump", Params: []GoType{GoByteSlice}, Returns: []GoType{GoString}},
			"encode":           {GoName: "Encode", Params: []GoType{GoByteSlice, GoByteSlice}, Returns: []GoType{GoInt}},
			"encode_to_string": {GoName: "EncodeToString", Params: []GoType{GoByteSlice}, Returns: []GoType{GoString}},
			// --- Skipped (need custom Codegen or _custom.go) ---
			// dumper (blocked): param 0: interface type
			// new_decoder (blocked): param 0: interface type
			// new_encoder (blocked): param 0: interface type
		},
	})
}
