// Code generated by rugo dev bridgegen; DO NOT EDIT.

package gobridge

func init() {
	Register(&Package{
		Path: "crypto/md5",
		Doc:  "Functions from Go's crypto/md5 package.",
		Funcs: map[string]GoFuncSig{
			"sum": {GoName: "Sum", Params: []GoType{GoByteSlice}, Returns: []GoType{GoByteSlice}, ArrayTypes: map[int]*GoArrayType{0: {Elem: GoByte, Size: 16}}},
			// --- Skipped (need custom Codegen or _custom.go) ---
			// new (blocked): return 0: interface type
		},
	})
}
