// Code generated by rugo dev bridgegen; DO NOT EDIT.

package gobridge

func init() {
	Register(&Package{
		Path: "os",
		Doc:  "Functions from Go's os package.",
		Funcs: map[string]GoFuncSig{
			"chdir":               {GoName: "Chdir", Params: []GoType{GoString}, Returns: []GoType{GoError}},
			"chown":               {GoName: "Chown", Params: []GoType{GoString, GoInt, GoInt}, Returns: []GoType{GoError}},
			"clearenv":            {GoName: "Clearenv", Params: nil, Returns: nil},
			"environ":             {GoName: "Environ", Params: nil, Returns: []GoType{GoStringSlice}},
			"executable":          {GoName: "Executable", Params: nil, Returns: []GoType{GoString, GoError}},
			"exit":                {GoName: "Exit", Params: []GoType{GoInt}, Returns: nil},
			"expand_env":          {GoName: "ExpandEnv", Params: []GoType{GoString}, Returns: []GoType{GoString}},
			"getegid":             {GoName: "Getegid", Params: nil, Returns: []GoType{GoInt}},
			"getenv":              {GoName: "Getenv", Params: []GoType{GoString}, Returns: []GoType{GoString}},
			"geteuid":             {GoName: "Geteuid", Params: nil, Returns: []GoType{GoInt}},
			"getgid":              {GoName: "Getgid", Params: nil, Returns: []GoType{GoInt}},
			"getpagesize":         {GoName: "Getpagesize", Params: nil, Returns: []GoType{GoInt}},
			"getpid":              {GoName: "Getpid", Params: nil, Returns: []GoType{GoInt}},
			"getppid":             {GoName: "Getppid", Params: nil, Returns: []GoType{GoInt}},
			"getuid":              {GoName: "Getuid", Params: nil, Returns: []GoType{GoInt}},
			"getwd":               {GoName: "Getwd", Params: nil, Returns: []GoType{GoString, GoError}},
			"hostname":            {GoName: "Hostname", Params: nil, Returns: []GoType{GoString, GoError}},
			"is_exist":            {GoName: "IsExist", Params: []GoType{GoError}, Returns: []GoType{GoBool}},
			"is_not_exist":        {GoName: "IsNotExist", Params: []GoType{GoError}, Returns: []GoType{GoBool}},
			"is_permission":       {GoName: "IsPermission", Params: []GoType{GoError}, Returns: []GoType{GoBool}},
			"is_timeout":          {GoName: "IsTimeout", Params: []GoType{GoError}, Returns: []GoType{GoBool}},
			"lchown":              {GoName: "Lchown", Params: []GoType{GoString, GoInt, GoInt}, Returns: []GoType{GoError}},
			"link":                {GoName: "Link", Params: []GoType{GoString, GoString}, Returns: []GoType{GoError}},
			"lookup_env":          {GoName: "LookupEnv", Params: []GoType{GoString}, Returns: []GoType{GoString, GoBool}},
			"mkdir_temp":          {GoName: "MkdirTemp", Params: []GoType{GoString, GoString}, Returns: []GoType{GoString, GoError}},
			"new_syscall_error":   {GoName: "NewSyscallError", Params: []GoType{GoString, GoError}, Returns: []GoType{GoError}},
			"readlink":            {GoName: "Readlink", Params: []GoType{GoString}, Returns: []GoType{GoString, GoError}},
			"remove":              {GoName: "Remove", Params: []GoType{GoString}, Returns: []GoType{GoError}},
			"remove_all":          {GoName: "RemoveAll", Params: []GoType{GoString}, Returns: []GoType{GoError}},
			"rename":              {GoName: "Rename", Params: []GoType{GoString, GoString}, Returns: []GoType{GoError}},
			"setenv":              {GoName: "Setenv", Params: []GoType{GoString, GoString}, Returns: []GoType{GoError}},
			"stderr_chdir":        {GoName: "Stderr.Chdir", Params: nil, Returns: []GoType{GoError}},
			"stderr_chown":        {GoName: "Stderr.Chown", Params: []GoType{GoInt, GoInt}, Returns: []GoType{GoError}},
			"stderr_close":        {GoName: "Stderr.Close", Params: nil, Returns: []GoType{GoError}},
			"stderr_name":         {GoName: "Stderr.Name", Params: nil, Returns: []GoType{GoString}},
			"stderr_readdirnames": {GoName: "Stderr.Readdirnames", Params: []GoType{GoInt}, Returns: []GoType{GoStringSlice, GoError}},
			"stderr_sync":         {GoName: "Stderr.Sync", Params: nil, Returns: []GoType{GoError}},
			"stderr_write_string": {GoName: "Stderr.WriteString", Params: []GoType{GoString}, Returns: []GoType{GoInt, GoError}},
			"stdin_chdir":         {GoName: "Stdin.Chdir", Params: nil, Returns: []GoType{GoError}},
			"stdin_chown":         {GoName: "Stdin.Chown", Params: []GoType{GoInt, GoInt}, Returns: []GoType{GoError}},
			"stdin_close":         {GoName: "Stdin.Close", Params: nil, Returns: []GoType{GoError}},
			"stdin_name":          {GoName: "Stdin.Name", Params: nil, Returns: []GoType{GoString}},
			"stdin_readdirnames":  {GoName: "Stdin.Readdirnames", Params: []GoType{GoInt}, Returns: []GoType{GoStringSlice, GoError}},
			"stdin_sync":          {GoName: "Stdin.Sync", Params: nil, Returns: []GoType{GoError}},
			"stdin_write_string":  {GoName: "Stdin.WriteString", Params: []GoType{GoString}, Returns: []GoType{GoInt, GoError}},
			"stdout_chdir":        {GoName: "Stdout.Chdir", Params: nil, Returns: []GoType{GoError}},
			"stdout_chown":        {GoName: "Stdout.Chown", Params: []GoType{GoInt, GoInt}, Returns: []GoType{GoError}},
			"stdout_close":        {GoName: "Stdout.Close", Params: nil, Returns: []GoType{GoError}},
			"stdout_name":         {GoName: "Stdout.Name", Params: nil, Returns: []GoType{GoString}},
			"stdout_readdirnames": {GoName: "Stdout.Readdirnames", Params: []GoType{GoInt}, Returns: []GoType{GoStringSlice, GoError}},
			"stdout_sync":         {GoName: "Stdout.Sync", Params: nil, Returns: []GoType{GoError}},
			"stdout_write_string": {GoName: "Stdout.WriteString", Params: []GoType{GoString}, Returns: []GoType{GoInt, GoError}},
			"symlink":             {GoName: "Symlink", Params: []GoType{GoString, GoString}, Returns: []GoType{GoError}},
			"temp_dir":            {GoName: "TempDir", Params: nil, Returns: []GoType{GoString}},
			"unsetenv":            {GoName: "Unsetenv", Params: []GoType{GoString}, Returns: []GoType{GoError}},
			"user_cache_dir":      {GoName: "UserCacheDir", Params: nil, Returns: []GoType{GoString, GoError}},
			"user_config_dir":     {GoName: "UserConfigDir", Params: nil, Returns: []GoType{GoString, GoError}},
			"user_home_dir":       {GoName: "UserHomeDir", Params: nil, Returns: []GoType{GoString, GoError}},
			"expand":              {GoName: "Expand", Params: []GoType{GoString, GoFunc}, Returns: []GoType{GoString}, FuncTypes: map[int]*GoFuncType{1: {Params: []GoType{GoString}, Returns: []GoType{GoString}}}},
			"is_path_separator":   {GoName: "IsPathSeparator", Params: []GoType{GoByte}, Returns: []GoType{GoBool}},
			"read_file":           {GoName: "ReadFile", Params: []GoType{GoString}, Returns: []GoType{GoByteSlice, GoError}},
			"stderr_read":         {GoName: "Stderr.Read", Params: []GoType{GoByteSlice}, Returns: []GoType{GoInt, GoError}},
			"stderr_read_at":      {GoName: "Stderr.ReadAt", Params: []GoType{GoByteSlice, GoInt64}, Returns: []GoType{GoInt, GoError}},
			"stderr_seek":         {GoName: "Stderr.Seek", Params: []GoType{GoInt64, GoInt}, Returns: []GoType{GoInt64, GoError}},
			"stderr_truncate":     {GoName: "Stderr.Truncate", Params: []GoType{GoInt64}, Returns: []GoType{GoError}},
			"stderr_write":        {GoName: "Stderr.Write", Params: []GoType{GoByteSlice}, Returns: []GoType{GoInt, GoError}},
			"stderr_write_at":     {GoName: "Stderr.WriteAt", Params: []GoType{GoByteSlice, GoInt64}, Returns: []GoType{GoInt, GoError}},
			"stdin_read":          {GoName: "Stdin.Read", Params: []GoType{GoByteSlice}, Returns: []GoType{GoInt, GoError}},
			"stdin_read_at":       {GoName: "Stdin.ReadAt", Params: []GoType{GoByteSlice, GoInt64}, Returns: []GoType{GoInt, GoError}},
			"stdin_seek":          {GoName: "Stdin.Seek", Params: []GoType{GoInt64, GoInt}, Returns: []GoType{GoInt64, GoError}},
			"stdin_truncate":      {GoName: "Stdin.Truncate", Params: []GoType{GoInt64}, Returns: []GoType{GoError}},
			"stdin_write":         {GoName: "Stdin.Write", Params: []GoType{GoByteSlice}, Returns: []GoType{GoInt, GoError}},
			"stdin_write_at":      {GoName: "Stdin.WriteAt", Params: []GoType{GoByteSlice, GoInt64}, Returns: []GoType{GoInt, GoError}},
			"stdout_read":         {GoName: "Stdout.Read", Params: []GoType{GoByteSlice}, Returns: []GoType{GoInt, GoError}},
			"stdout_read_at":      {GoName: "Stdout.ReadAt", Params: []GoType{GoByteSlice, GoInt64}, Returns: []GoType{GoInt, GoError}},
			"stdout_seek":         {GoName: "Stdout.Seek", Params: []GoType{GoInt64, GoInt}, Returns: []GoType{GoInt64, GoError}},
			"stdout_truncate":     {GoName: "Stdout.Truncate", Params: []GoType{GoInt64}, Returns: []GoType{GoError}},
			"stdout_write":        {GoName: "Stdout.Write", Params: []GoType{GoByteSlice}, Returns: []GoType{GoInt, GoError}},
			"stdout_write_at":     {GoName: "Stdout.WriteAt", Params: []GoType{GoByteSlice, GoInt64}, Returns: []GoType{GoInt, GoError}},
			"truncate":            {GoName: "Truncate", Params: []GoType{GoString, GoInt64}, Returns: []GoType{GoError}},
			// --- Skipped (need custom Codegen or _custom.go) ---
			// chmod (blocked): param 1: unknown type *types.Alias
			// chtimes (blocked): param 1: struct type
			// copy_fs (blocked): param 1: interface type
			// create (blocked): return 0: pointer to os.File
			// create_temp (blocked): return 0: pointer to os.File
			// dir_fs (blocked): return 0: interface type
			// find_process (blocked): return 0: pointer to os.Process
			// getgroups (blocked): return 0: unsupported slice type []int
			// lstat (blocked): return 0: unknown type *types.Alias
			// mkdir (blocked): param 1: unknown type *types.Alias
			// mkdir_all (blocked): param 1: unknown type *types.Alias
			// new_file (blocked): param 0: unsupported basic type uintptr
			// open (blocked): return 0: pointer to os.File
			// open_file (blocked): param 2: unknown type *types.Alias
			// open_in_root (blocked): return 0: pointer to os.File
			// open_root (blocked): return 0: pointer to os.Root
			// pipe (blocked): return 0: pointer to os.File
			// read_dir (blocked): return 0: unsupported slice type []os.DirEntry
			// same_file (blocked): param 0: unknown type *types.Alias
			// start_process (blocked): param 2: pointer to os.ProcAttr
			// stat (blocked): return 0: unknown type *types.Alias
			// stderr_chmod (blocked): param 0: unknown type *types.Alias
			// stderr_fd (blocked): return 0: unsupported basic type uintptr
			// stderr_read_dir (blocked): return 0: unsupported slice type []os.DirEntry
			// stderr_read_from (blocked): param 0: interface type
			// stderr_readdir (blocked): return 0: unsupported slice type []os.FileInfo
			// stderr_set_deadline (blocked): param 0: struct type
			// stderr_set_read_deadline (blocked): param 0: struct type
			// stderr_set_write_deadline (blocked): param 0: struct type
			// stderr_stat (blocked): return 0: unknown type *types.Alias
			// stderr_syscall_conn (blocked): return 0: interface type
			// stderr_write_to (blocked): param 0: interface type
			// stdin_chmod (blocked): param 0: unknown type *types.Alias
			// stdin_fd (blocked): return 0: unsupported basic type uintptr
			// stdin_read_dir (blocked): return 0: unsupported slice type []os.DirEntry
			// stdin_read_from (blocked): param 0: interface type
			// stdin_readdir (blocked): return 0: unsupported slice type []os.FileInfo
			// stdin_set_deadline (blocked): param 0: struct type
			// stdin_set_read_deadline (blocked): param 0: struct type
			// stdin_set_write_deadline (blocked): param 0: struct type
			// stdin_stat (blocked): return 0: unknown type *types.Alias
			// stdin_syscall_conn (blocked): return 0: interface type
			// stdin_write_to (blocked): param 0: interface type
			// stdout_chmod (blocked): param 0: unknown type *types.Alias
			// stdout_fd (blocked): return 0: unsupported basic type uintptr
			// stdout_read_dir (blocked): return 0: unsupported slice type []os.DirEntry
			// stdout_read_from (blocked): param 0: interface type
			// stdout_readdir (blocked): return 0: unsupported slice type []os.FileInfo
			// stdout_set_deadline (blocked): param 0: struct type
			// stdout_set_read_deadline (blocked): param 0: struct type
			// stdout_set_write_deadline (blocked): param 0: struct type
			// stdout_stat (blocked): return 0: unknown type *types.Alias
			// stdout_syscall_conn (blocked): return 0: interface type
			// stdout_write_to (blocked): param 0: interface type
			// write_file (blocked): param 2: unknown type *types.Alias
		},
	})
}
