// Code generated by rugo dev bridgegen; DO NOT EDIT.

package gobridge

func init() {
	Register(&Package{
		Path: "math/rand/v2",
		Doc:  "Functions from Go's math/rand/v2 package.",
		Funcs: map[string]GoFuncSig{
			"exp_float64":  {GoName: "ExpFloat64", Params: nil, Returns: []GoType{GoFloat64}},
			"float64":      {GoName: "Float64", Params: nil, Returns: []GoType{GoFloat64}},
			"int":          {GoName: "Int", Params: nil, Returns: []GoType{GoInt}},
			"int_n":        {GoName: "IntN", Params: []GoType{GoInt}, Returns: []GoType{GoInt}},
			"norm_float64": {GoName: "NormFloat64", Params: nil, Returns: []GoType{GoFloat64}},
			"float32":      {GoName: "Float32", Params: nil, Returns: []GoType{GoFloat32}},
			"int32":        {GoName: "Int32", Params: nil, Returns: []GoType{GoInt32}},
			"int32_n":      {GoName: "Int32N", Params: []GoType{GoInt32}, Returns: []GoType{GoInt32}},
			"int64":        {GoName: "Int64", Params: nil, Returns: []GoType{GoInt64}},
			"int64_n":      {GoName: "Int64N", Params: []GoType{GoInt64}, Returns: []GoType{GoInt64}},
			"shuffle":      {GoName: "Shuffle", Params: []GoType{GoInt, GoFunc}, Returns: nil, FuncTypes: map[int]*GoFuncType{1: {Params: []GoType{GoInt, GoInt}, Returns: nil}}},
			"uint":         {GoName: "Uint", Params: nil, Returns: []GoType{GoUint}},
			"uint32":       {GoName: "Uint32", Params: nil, Returns: []GoType{GoUint32}},
			"uint32_n":     {GoName: "Uint32N", Params: []GoType{GoUint32}, Returns: []GoType{GoUint32}},
			"uint64":       {GoName: "Uint64", Params: nil, Returns: []GoType{GoUint64}},
			"uint64_n":     {GoName: "Uint64N", Params: []GoType{GoUint64}, Returns: []GoType{GoUint64}},
			"uint_n":       {GoName: "UintN", Params: []GoType{GoUint}, Returns: []GoType{GoUint}},
			// --- Skipped (need custom Codegen or _custom.go) ---
			// n (blocked): param 0: unknown type *types.TypeParam
			// new (blocked): param 0: interface type
			// new_cha_cha8 (blocked): return 0: pointer to math/rand/v2.ChaCha8
			// new_pcg (blocked): return 0: pointer to math/rand/v2.PCG
			// new_zipf (blocked): param 0: pointer to math/rand/v2.Rand
			// perm (blocked): return 0: unsupported slice type []int
		},
	})
}
