// Code generated by rugo dev bridgegen; DO NOT EDIT.

package gobridge

func init() {
	Register(&Package{
		Path: "crypto/sha256",
		Doc:  "Functions from Go's crypto/sha256 package.",
		Funcs: map[string]GoFuncSig{
			"sum224": {GoName: "Sum224", Params: []GoType{GoByteSlice}, Returns: []GoType{GoByteSlice}, ArrayTypes: map[int]*GoArrayType{0: {Elem: GoByte, Size: 28}}},
			"sum256": {GoName: "Sum256", Params: []GoType{GoByteSlice}, Returns: []GoType{GoByteSlice}, ArrayTypes: map[int]*GoArrayType{0: {Elem: GoByte, Size: 32}}},
			// --- Skipped (need custom Codegen or _custom.go) ---
			// new (blocked): return 0: interface type
			// new224 (blocked): return 0: interface type
		},
	})
}
