// Code generated by rugo dev bridgegen; DO NOT EDIT.

package gobridge

func init() {
	Register(&Package{
		Path: "strconv",
		Doc:  "Functions from Go's strconv package.",
		Funcs: map[string]GoFuncSig{
			"atoi":                         {GoName: "Atoi", Params: []GoType{GoString}, Returns: []GoType{GoInt, GoError}},
			"can_backquote":                {GoName: "CanBackquote", Params: []GoType{GoString}, Returns: []GoType{GoBool}},
			"format_bool":                  {GoName: "FormatBool", Params: []GoType{GoBool}, Returns: []GoType{GoString}},
			"itoa":                         {GoName: "Itoa", Params: []GoType{GoInt}, Returns: []GoType{GoString}},
			"parse_bool":                   {GoName: "ParseBool", Params: []GoType{GoString}, Returns: []GoType{GoBool, GoError}},
			"parse_float":                  {GoName: "ParseFloat", Params: []GoType{GoString, GoInt}, Returns: []GoType{GoFloat64, GoError}},
			"quote":                        {GoName: "Quote", Params: []GoType{GoString}, Returns: []GoType{GoString}},
			"quote_to_ascii":               {GoName: "QuoteToASCII", Params: []GoType{GoString}, Returns: []GoType{GoString}},
			"quote_to_graphic":             {GoName: "QuoteToGraphic", Params: []GoType{GoString}, Returns: []GoType{GoString}},
			"quoted_prefix":                {GoName: "QuotedPrefix", Params: []GoType{GoString}, Returns: []GoType{GoString, GoError}},
			"unquote":                      {GoName: "Unquote", Params: []GoType{GoString}, Returns: []GoType{GoString, GoError}},
			"append_bool":                  {GoName: "AppendBool", Params: []GoType{GoByteSlice, GoBool}, Returns: []GoType{GoByteSlice}},
			"append_float":                 {GoName: "AppendFloat", Params: []GoType{GoByteSlice, GoFloat64, GoByte, GoInt, GoInt}, Returns: []GoType{GoByteSlice}},
			"append_int":                   {GoName: "AppendInt", Params: []GoType{GoByteSlice, GoInt64, GoInt}, Returns: []GoType{GoByteSlice}},
			"append_quote":                 {GoName: "AppendQuote", Params: []GoType{GoByteSlice, GoString}, Returns: []GoType{GoByteSlice}},
			"append_quote_rune":            {GoName: "AppendQuoteRune", Params: []GoType{GoByteSlice, GoRune}, Returns: []GoType{GoByteSlice}},
			"append_quote_rune_to_ascii":   {GoName: "AppendQuoteRuneToASCII", Params: []GoType{GoByteSlice, GoRune}, Returns: []GoType{GoByteSlice}},
			"append_quote_rune_to_graphic": {GoName: "AppendQuoteRuneToGraphic", Params: []GoType{GoByteSlice, GoRune}, Returns: []GoType{GoByteSlice}},
			"append_quote_to_ascii":        {GoName: "AppendQuoteToASCII", Params: []GoType{GoByteSlice, GoString}, Returns: []GoType{GoByteSlice}},
			"append_quote_to_graphic":      {GoName: "AppendQuoteToGraphic", Params: []GoType{GoByteSlice, GoString}, Returns: []GoType{GoByteSlice}},
			"append_uint":                  {GoName: "AppendUint", Params: []GoType{GoByteSlice, GoUint64, GoInt}, Returns: []GoType{GoByteSlice}},
			"format_float":                 {GoName: "FormatFloat", Params: []GoType{GoFloat64, GoByte, GoInt, GoInt}, Returns: []GoType{GoString}},
			"format_int":                   {GoName: "FormatInt", Params: []GoType{GoInt64, GoInt}, Returns: []GoType{GoString}},
			"format_uint":                  {GoName: "FormatUint", Params: []GoType{GoUint64, GoInt}, Returns: []GoType{GoString}},
			"is_graphic":                   {GoName: "IsGraphic", Params: []GoType{GoRune}, Returns: []GoType{GoBool}},
			"is_print":                     {GoName: "IsPrint", Params: []GoType{GoRune}, Returns: []GoType{GoBool}},
			"parse_int":                    {GoName: "ParseInt", Params: []GoType{GoString, GoInt, GoInt}, Returns: []GoType{GoInt64, GoError}},
			"parse_uint":                   {GoName: "ParseUint", Params: []GoType{GoString, GoInt, GoInt}, Returns: []GoType{GoUint64, GoError}},
			"quote_rune":                   {GoName: "QuoteRune", Params: []GoType{GoRune}, Returns: []GoType{GoString}},
			"quote_rune_to_ascii":          {GoName: "QuoteRuneToASCII", Params: []GoType{GoRune}, Returns: []GoType{GoString}},
			"quote_rune_to_graphic":        {GoName: "QuoteRuneToGraphic", Params: []GoType{GoRune}, Returns: []GoType{GoString}},
			"unquote_char":                 {GoName: "UnquoteChar", Params: []GoType{GoString, GoByte}, Returns: []GoType{GoRune, GoBool, GoString, GoError}},
			// --- Skipped (need custom Codegen or _custom.go) ---
			// format_complex (blocked): param 0: unsupported basic type complex128
			// parse_complex (blocked): return 0: unsupported basic type complex128
		},
	})
}
