package gobridge

func init() {
	Register(&Package{
		Path: "strings",
		Doc:  "String manipulation functions from Go's strings package.",
		Funcs: map[string]GoFuncSig{
			"contains":       {GoName: "Contains", Params: []GoType{GoString, GoString}, Returns: []GoType{GoBool}, Doc: "Reports whether substr is within s."},
			"contains_any":   {GoName: "ContainsAny", Params: []GoType{GoString, GoString}, Returns: []GoType{GoBool}, Doc: "Reports whether any char in chars is within s."},
			"count":          {GoName: "Count", Params: []GoType{GoString, GoString}, Returns: []GoType{GoInt}, Doc: "Counts non-overlapping instances of substr in s."},
			"has_prefix":     {GoName: "HasPrefix", Params: []GoType{GoString, GoString}, Returns: []GoType{GoBool}, Doc: "Reports whether s begins with prefix."},
			"has_suffix":     {GoName: "HasSuffix", Params: []GoType{GoString, GoString}, Returns: []GoType{GoBool}, Doc: "Reports whether s ends with suffix."},
			"index":          {GoName: "Index", Params: []GoType{GoString, GoString}, Returns: []GoType{GoInt}, Doc: "Returns the index of the first instance of substr, or -1."},
			"join":           {GoName: "Join", Params: []GoType{GoStringSlice, GoString}, Returns: []GoType{GoString}, Doc: "Concatenates array elements with separator.", RuntimeHelpers: stringSliceHelpers},
			"last_index":     {GoName: "LastIndex", Params: []GoType{GoString, GoString}, Returns: []GoType{GoInt}, Doc: "Returns the index of the last instance of substr, or -1."},
			"repeat":         {GoName: "Repeat", Params: []GoType{GoString, GoInt}, Returns: []GoType{GoString}, Doc: "Returns s repeated count times."},
			"replace":        {GoName: "Replace", Params: []GoType{GoString, GoString, GoString, GoInt}, Returns: []GoType{GoString}, Doc: "Replaces first n occurrences of old with new in s."},
			"replace_all":    {GoName: "ReplaceAll", Params: []GoType{GoString, GoString, GoString}, Returns: []GoType{GoString}, Doc: "Replaces all occurrences of old with new in s."},
			"split":          {GoName: "Split", Params: []GoType{GoString, GoString}, Returns: []GoType{GoStringSlice}, Doc: "Splits s around each instance of sep.", RuntimeHelpers: stringSliceHelpers},
			"split_n":        {GoName: "SplitN", Params: []GoType{GoString, GoString, GoInt}, Returns: []GoType{GoStringSlice}, Doc: "Splits s into at most n substrings.", RuntimeHelpers: stringSliceHelpers},
			"to_lower":       {GoName: "ToLower", Params: []GoType{GoString}, Returns: []GoType{GoString}, Doc: "Returns s with all characters lowercased."},
			"to_upper":       {GoName: "ToUpper", Params: []GoType{GoString}, Returns: []GoType{GoString}, Doc: "Returns s with all characters uppercased."},
			"to_title":       {GoName: "ToTitle", Params: []GoType{GoString}, Returns: []GoType{GoString}, Doc: "Returns s with all characters title-cased."},
			"trim":           {GoName: "Trim", Params: []GoType{GoString, GoString}, Returns: []GoType{GoString}, Doc: "Trims leading and trailing characters in cutset from s."},
			"trim_left":      {GoName: "TrimLeft", Params: []GoType{GoString, GoString}, Returns: []GoType{GoString}, Doc: "Trims leading characters in cutset from s."},
			"trim_right":     {GoName: "TrimRight", Params: []GoType{GoString, GoString}, Returns: []GoType{GoString}, Doc: "Trims trailing characters in cutset from s."},
			"trim_space":     {GoName: "TrimSpace", Params: []GoType{GoString}, Returns: []GoType{GoString}, Doc: "Trims leading and trailing whitespace from s."},
			"trim_prefix":    {GoName: "TrimPrefix", Params: []GoType{GoString, GoString}, Returns: []GoType{GoString}, Doc: "Removes the prefix from s if present."},
			"trim_suffix":    {GoName: "TrimSuffix", Params: []GoType{GoString, GoString}, Returns: []GoType{GoString}, Doc: "Removes the suffix from s if present."},
			"equal_fold":     {GoName: "EqualFold", Params: []GoType{GoString, GoString}, Returns: []GoType{GoBool}, Doc: "Reports whether s and t are equal under case-folding."},
			"clone":          {GoName: "Clone", Params: []GoType{GoString}, Returns: []GoType{GoString}, Doc: "Returns a fresh copy of s."},
			"compare":        {GoName: "Compare", Params: []GoType{GoString, GoString}, Returns: []GoType{GoInt}, Doc: "Returns -1, 0, or 1 comparing two strings lexicographically."},
			"cut":            {GoName: "Cut", Params: []GoType{GoString, GoString}, Returns: []GoType{GoString, GoString, GoBool}, Doc: "Cuts s around the first instance of sep."},
			"cut_prefix":     {GoName: "CutPrefix", Params: []GoType{GoString, GoString}, Returns: []GoType{GoString, GoBool}, Doc: "Removes the prefix and reports whether it was found."},
			"cut_suffix":     {GoName: "CutSuffix", Params: []GoType{GoString, GoString}, Returns: []GoType{GoString, GoBool}, Doc: "Removes the suffix and reports whether it was found."},
			"fields":         {GoName: "Fields", Params: []GoType{GoString}, Returns: []GoType{GoStringSlice}, Doc: "Splits s around whitespace into an array of substrings.", RuntimeHelpers: stringSliceHelpers},
			"index_any":      {GoName: "IndexAny", Params: []GoType{GoString, GoString}, Returns: []GoType{GoInt}, Doc: "Returns the index of the first char from chars found in s, or -1."},
			"last_index_any": {GoName: "LastIndexAny", Params: []GoType{GoString, GoString}, Returns: []GoType{GoInt}, Doc: "Returns the index of the last char from chars found in s, or -1."},
			"contains_func": {
				GoName: "ContainsFunc", Params: []GoType{GoString, GoFunc}, Returns: []GoType{GoBool},
				Doc:       "Reports whether any character in s satisfies the predicate f.",
				FuncTypes: map[int]*GoFuncType{1: {Params: []GoType{GoRune}, Returns: []GoType{GoBool}}},
			},
			"index_func": {
				GoName: "IndexFunc", Params: []GoType{GoString, GoFunc}, Returns: []GoType{GoInt},
				Doc:       "Returns the index of the first character satisfying the predicate f, or -1.",
				FuncTypes: map[int]*GoFuncType{1: {Params: []GoType{GoRune}, Returns: []GoType{GoBool}}},
			},
			"map": {
				GoName: "Map", Params: []GoType{GoFunc, GoString}, Returns: []GoType{GoString},
				Doc:       "Returns a copy of s with all characters modified by the mapping function.",
				FuncTypes: map[int]*GoFuncType{0: {Params: []GoType{GoRune}, Returns: []GoType{GoRune}}},
			},
		},
	})
}
