// Code generated by rugo dev bridgegen; DO NOT EDIT.

package gobridge

func init() {
	Register(&Package{
		Path: "strings",
		Doc:  "Functions from Go's strings package.",
		Funcs: map[string]GoFuncSig{
			"clone":           {GoName: "Clone", Params: []GoType{GoString}, Returns: []GoType{GoString}},
			"compare":         {GoName: "Compare", Params: []GoType{GoString, GoString}, Returns: []GoType{GoInt}},
			"contains":        {GoName: "Contains", Params: []GoType{GoString, GoString}, Returns: []GoType{GoBool}},
			"contains_any":    {GoName: "ContainsAny", Params: []GoType{GoString, GoString}, Returns: []GoType{GoBool}},
			"count":           {GoName: "Count", Params: []GoType{GoString, GoString}, Returns: []GoType{GoInt}},
			"cut":             {GoName: "Cut", Params: []GoType{GoString, GoString}, Returns: []GoType{GoString, GoString, GoBool}},
			"cut_prefix":      {GoName: "CutPrefix", Params: []GoType{GoString, GoString}, Returns: []GoType{GoString, GoBool}},
			"cut_suffix":      {GoName: "CutSuffix", Params: []GoType{GoString, GoString}, Returns: []GoType{GoString, GoBool}},
			"equal_fold":      {GoName: "EqualFold", Params: []GoType{GoString, GoString}, Returns: []GoType{GoBool}},
			"fields":          {GoName: "Fields", Params: []GoType{GoString}, Returns: []GoType{GoStringSlice}},
			"fields_seq":      {GoName: "FieldsSeq", Params: []GoType{GoString}, Returns: []GoType{GoFunc}},
			"has_prefix":      {GoName: "HasPrefix", Params: []GoType{GoString, GoString}, Returns: []GoType{GoBool}},
			"has_suffix":      {GoName: "HasSuffix", Params: []GoType{GoString, GoString}, Returns: []GoType{GoBool}},
			"index":           {GoName: "Index", Params: []GoType{GoString, GoString}, Returns: []GoType{GoInt}},
			"index_any":       {GoName: "IndexAny", Params: []GoType{GoString, GoString}, Returns: []GoType{GoInt}},
			"join":            {GoName: "Join", Params: []GoType{GoStringSlice, GoString}, Returns: []GoType{GoString}},
			"last_index":      {GoName: "LastIndex", Params: []GoType{GoString, GoString}, Returns: []GoType{GoInt}},
			"last_index_any":  {GoName: "LastIndexAny", Params: []GoType{GoString, GoString}, Returns: []GoType{GoInt}},
			"lines":           {GoName: "Lines", Params: []GoType{GoString}, Returns: []GoType{GoFunc}},
			"repeat":          {GoName: "Repeat", Params: []GoType{GoString, GoInt}, Returns: []GoType{GoString}},
			"replace":         {GoName: "Replace", Params: []GoType{GoString, GoString, GoString, GoInt}, Returns: []GoType{GoString}},
			"replace_all":     {GoName: "ReplaceAll", Params: []GoType{GoString, GoString, GoString}, Returns: []GoType{GoString}},
			"split":           {GoName: "Split", Params: []GoType{GoString, GoString}, Returns: []GoType{GoStringSlice}},
			"split_after":     {GoName: "SplitAfter", Params: []GoType{GoString, GoString}, Returns: []GoType{GoStringSlice}},
			"split_after_n":   {GoName: "SplitAfterN", Params: []GoType{GoString, GoString, GoInt}, Returns: []GoType{GoStringSlice}},
			"split_after_seq": {GoName: "SplitAfterSeq", Params: []GoType{GoString, GoString}, Returns: []GoType{GoFunc}},
			"split_n":         {GoName: "SplitN", Params: []GoType{GoString, GoString, GoInt}, Returns: []GoType{GoStringSlice}},
			"split_seq":       {GoName: "SplitSeq", Params: []GoType{GoString, GoString}, Returns: []GoType{GoFunc}},
			"title":           {GoName: "Title", Params: []GoType{GoString}, Returns: []GoType{GoString}},
			"to_lower":        {GoName: "ToLower", Params: []GoType{GoString}, Returns: []GoType{GoString}},
			"to_title":        {GoName: "ToTitle", Params: []GoType{GoString}, Returns: []GoType{GoString}},
			"to_upper":        {GoName: "ToUpper", Params: []GoType{GoString}, Returns: []GoType{GoString}},
			"to_valid_utf_8":  {GoName: "ToValidUTF8", Params: []GoType{GoString, GoString}, Returns: []GoType{GoString}},
			"trim":            {GoName: "Trim", Params: []GoType{GoString, GoString}, Returns: []GoType{GoString}},
			"trim_left":       {GoName: "TrimLeft", Params: []GoType{GoString, GoString}, Returns: []GoType{GoString}},
			"trim_prefix":     {GoName: "TrimPrefix", Params: []GoType{GoString, GoString}, Returns: []GoType{GoString}},
			"trim_right":      {GoName: "TrimRight", Params: []GoType{GoString, GoString}, Returns: []GoType{GoString}},
			"trim_space":      {GoName: "TrimSpace", Params: []GoType{GoString}, Returns: []GoType{GoString}},
			"trim_suffix":     {GoName: "TrimSuffix", Params: []GoType{GoString, GoString}, Returns: []GoType{GoString}},
			"contains_func":   {GoName: "ContainsFunc", Params: []GoType{GoString, GoFunc}, Returns: []GoType{GoBool}, FuncTypes: map[int]*GoFuncType{1: {Params: []GoType{GoRune}, Returns: []GoType{GoBool}}}},
			"contains_rune":   {GoName: "ContainsRune", Params: []GoType{GoString, GoRune}, Returns: []GoType{GoBool}},
			"fields_func":     {GoName: "FieldsFunc", Params: []GoType{GoString, GoFunc}, Returns: []GoType{GoStringSlice}, FuncTypes: map[int]*GoFuncType{1: {Params: []GoType{GoRune}, Returns: []GoType{GoBool}}}},
			"fields_func_seq": {GoName: "FieldsFuncSeq", Params: []GoType{GoString, GoFunc}, Returns: []GoType{GoFunc}, FuncTypes: map[int]*GoFuncType{1: {Params: []GoType{GoRune}, Returns: []GoType{GoBool}}}},
			"index_byte":      {GoName: "IndexByte", Params: []GoType{GoString, GoByte}, Returns: []GoType{GoInt}},
			"index_func":      {GoName: "IndexFunc", Params: []GoType{GoString, GoFunc}, Returns: []GoType{GoInt}, FuncTypes: map[int]*GoFuncType{1: {Params: []GoType{GoRune}, Returns: []GoType{GoBool}}}},
			"index_rune":      {GoName: "IndexRune", Params: []GoType{GoString, GoRune}, Returns: []GoType{GoInt}},
			"last_index_byte": {GoName: "LastIndexByte", Params: []GoType{GoString, GoByte}, Returns: []GoType{GoInt}},
			"last_index_func": {GoName: "LastIndexFunc", Params: []GoType{GoString, GoFunc}, Returns: []GoType{GoInt}, FuncTypes: map[int]*GoFuncType{1: {Params: []GoType{GoRune}, Returns: []GoType{GoBool}}}},
			"map":             {GoName: "Map", Params: []GoType{GoFunc, GoString}, Returns: []GoType{GoString}, FuncTypes: map[int]*GoFuncType{0: {Params: []GoType{GoRune}, Returns: []GoType{GoRune}}}},
			"trim_func":       {GoName: "TrimFunc", Params: []GoType{GoString, GoFunc}, Returns: []GoType{GoString}, FuncTypes: map[int]*GoFuncType{1: {Params: []GoType{GoRune}, Returns: []GoType{GoBool}}}},
			"trim_left_func":  {GoName: "TrimLeftFunc", Params: []GoType{GoString, GoFunc}, Returns: []GoType{GoString}, FuncTypes: map[int]*GoFuncType{1: {Params: []GoType{GoRune}, Returns: []GoType{GoBool}}}},
			"trim_right_func": {GoName: "TrimRightFunc", Params: []GoType{GoString, GoFunc}, Returns: []GoType{GoString}, FuncTypes: map[int]*GoFuncType{1: {Params: []GoType{GoRune}, Returns: []GoType{GoBool}}}},
			// --- Skipped (need custom Codegen or _custom.go) ---
			// new_reader (blocked): return 0: pointer to strings.Reader
			// new_replacer (blocked): return 0: pointer to strings.Replacer
			// to_lower_special (blocked): param 0: unsupported slice type []unicode.CaseRange
			// to_title_special (blocked): param 0: unsupported slice type []unicode.CaseRange
			// to_upper_special (blocked): param 0: unsupported slice type []unicode.CaseRange
		},
	})
}
