// Code generated by rugo dev bridgegen; DO NOT EDIT.

package gobridge

func init() {
	Register(&Package{
		Path: "time",
		Doc:  "Functions from Go's time package.",
		Funcs: map[string]GoFuncSig{
			"local_string":   {GoName: "Local.String", Params: nil, Returns: []GoType{GoString}},
			"utc_string":     {GoName: "UTC.String", Params: nil, Returns: []GoType{GoString}},
			"parse_duration": {GoName: "ParseDuration", Params: []GoType{GoString}, Returns: []GoType{GoInt64, GoError}},
			"sleep":          {GoName: "Sleep", Params: []GoType{GoInt64}, Returns: nil},
			// --- Skipped (need custom Codegen or _custom.go) ---
			// after (blocked): return 0: channel type
			// after_func (blocked): return 0: pointer to time.Timer
			// date (blocked): param 7: pointer to time.Location
			// fixed_zone (blocked): return 0: pointer to time.Location
			// load_location (blocked): return 0: pointer to time.Location
			// load_location_from_tzdata (blocked): return 0: pointer to time.Location
			// new_ticker (blocked): return 0: pointer to time.Ticker
			// new_timer (blocked): return 0: pointer to time.Timer
			// now (blocked): return 0: struct type
			// parse (blocked): return 0: struct type
			// parse_in_location (blocked): param 2: pointer to time.Location
			// since (blocked): param 0: struct type
			// tick (blocked): return 0: channel type
			// unix (blocked): return 0: struct type
			// unix_micro (blocked): return 0: struct type
			// unix_milli (blocked): return 0: struct type
			// until (blocked): param 0: struct type
		},
	})
}
