// Code generated by rugo dev bridgegen; DO NOT EDIT.

package gobridge

func init() {
	Register(&Package{
		Path: "unicode",
		Doc:  "Functions from Go's unicode package.",
		Funcs: map[string]GoFuncSig{
			"azeri_case_to_lower":   {GoName: "AzeriCase.ToLower", Params: []GoType{GoRune}, Returns: []GoType{GoRune}},
			"azeri_case_to_title":   {GoName: "AzeriCase.ToTitle", Params: []GoType{GoRune}, Returns: []GoType{GoRune}},
			"azeri_case_to_upper":   {GoName: "AzeriCase.ToUpper", Params: []GoType{GoRune}, Returns: []GoType{GoRune}},
			"is_control":            {GoName: "IsControl", Params: []GoType{GoRune}, Returns: []GoType{GoBool}},
			"is_digit":              {GoName: "IsDigit", Params: []GoType{GoRune}, Returns: []GoType{GoBool}},
			"is_graphic":            {GoName: "IsGraphic", Params: []GoType{GoRune}, Returns: []GoType{GoBool}},
			"is_letter":             {GoName: "IsLetter", Params: []GoType{GoRune}, Returns: []GoType{GoBool}},
			"is_lower":              {GoName: "IsLower", Params: []GoType{GoRune}, Returns: []GoType{GoBool}},
			"is_mark":               {GoName: "IsMark", Params: []GoType{GoRune}, Returns: []GoType{GoBool}},
			"is_number":             {GoName: "IsNumber", Params: []GoType{GoRune}, Returns: []GoType{GoBool}},
			"is_print":              {GoName: "IsPrint", Params: []GoType{GoRune}, Returns: []GoType{GoBool}},
			"is_punct":              {GoName: "IsPunct", Params: []GoType{GoRune}, Returns: []GoType{GoBool}},
			"is_space":              {GoName: "IsSpace", Params: []GoType{GoRune}, Returns: []GoType{GoBool}},
			"is_symbol":             {GoName: "IsSymbol", Params: []GoType{GoRune}, Returns: []GoType{GoBool}},
			"is_title":              {GoName: "IsTitle", Params: []GoType{GoRune}, Returns: []GoType{GoBool}},
			"is_upper":              {GoName: "IsUpper", Params: []GoType{GoRune}, Returns: []GoType{GoBool}},
			"simple_fold":           {GoName: "SimpleFold", Params: []GoType{GoRune}, Returns: []GoType{GoRune}},
			"to":                    {GoName: "To", Params: []GoType{GoInt, GoRune}, Returns: []GoType{GoRune}},
			"to_lower":              {GoName: "ToLower", Params: []GoType{GoRune}, Returns: []GoType{GoRune}},
			"to_title":              {GoName: "ToTitle", Params: []GoType{GoRune}, Returns: []GoType{GoRune}},
			"to_upper":              {GoName: "ToUpper", Params: []GoType{GoRune}, Returns: []GoType{GoRune}},
			"turkish_case_to_lower": {GoName: "TurkishCase.ToLower", Params: []GoType{GoRune}, Returns: []GoType{GoRune}},
			"turkish_case_to_title": {GoName: "TurkishCase.ToTitle", Params: []GoType{GoRune}, Returns: []GoType{GoRune}},
			"turkish_case_to_upper": {GoName: "TurkishCase.ToUpper", Params: []GoType{GoRune}, Returns: []GoType{GoRune}},
			// --- Skipped (need custom Codegen or _custom.go) ---
			// in (blocked): param 1: unsupported slice type []*unicode.RangeTable
			// is (blocked): param 0: pointer to unicode.RangeTable
			// is_one_of (blocked): param 0: unsupported slice type []*unicode.RangeTable
		},
	})
}
